homepage/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
	path('', views.landingpage, name='landingpage'),
    path('login/', views.loginpage, name='loginpage'),
    path('menu/', views.menupage, name='menupage'),
    path('logout/',views.logoutpage, name='logoutpage'),
]

story9/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.
def loginpage(request):
	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			user = form.get_user()
			login(request, user)
			return redirect('homepage:menupage')
	else:
		form = AuthenticationForm()
	return render(request, 'login.html', {'form':form})

def landingpage(request):
	return render(request, 'landing.html')

def menupage(request):
	if request.user.is_authenticated:
		return render(request,'menu.html')
	else:
		return redirect('homepage:loginpage')

def logoutpage(request):
	if request.user.is_authenticated:
		if request.method == 'POST':
			logout(request)
	return redirect('homepage:landingpage')

homepage/templates/landing.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>Story 9</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body style="text-align: center;">
	<h1 style="margin-top: 10%; ">Wanna Log in?</h1>
	{% if not user.is_authenticated %}
	<a  href="{%url 'homepage:loginpage' %}" style="margin-top: 6%;">Click Here</a>
	{% endif %}
</body>

homepage/templates/login.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
    <title>Story 9</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body style="text-align: center;">
	 <h1 style="margin-top: 10%;" >Login</h1>
	 <form style="margin-top: 5%;" class="site-form" action="{%url 'homepage:loginpage' %}" method="post">
	 	{% csrf_token %}
	 	<div id="flexbox-container">
	 	{{form.as_p}}
	 	</div>
	 	<input type="submit" value="Login">
	 </form>
</body>

homepage/templates/menu.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>Story 9</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body style="text-align: center;">
	<h1 style="margin-top: 10%;">You're Logged In</h1>
	{% if user.is_authenticated %}
	<h3 style="margin-top: 5%;">Welcome, {{ user.username }}!</h3>
	<form class="logout-link" action="{%url 'homepage:logoutpage' %}" method="post">
		{% csrf_token %}
		<button class="btn btn-dark" type="submit">Logout</button>
	</form>
	{% endif %}
	
</body>